import re

with open('Entrada/2026/Março/embargos_declaracao_5028845-33.2023.4.04.7200.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# Ordered replacements (longer first to avoid partial matches)
replacements = [
    # Multi-word / longer first
    ('SINTESE ARGUMENTATIVA', 'SÍNTESE ARGUMENTATIVA'),
    ('CONCLUSAO E PEDIDOS', 'CONCLUSÃO E PEDIDOS'),
    ('DECISAO EMBARGADA', 'DECISÃO EMBARGADA'),
    ('QUESTAO DE DIREITO', 'QUESTÃO DE DIREITO'),
    ('ERRO MATERIAL NA PREMISSA DA DECISAO', 'ERRO MATERIAL NA PREMISSA DA DECISÃO'),
    ('COMPOSICAO DA RENDA', 'COMPOSIÇÃO DA RENDA'),
    ('socioeconomica', 'socioeconômica'),
    ('socioeconomico', 'socioeconômico'),
    ('fatico-juridica', 'fático-jurídica'),
    ('FATICO-JURIDICA', 'FÁTICO-JURÍDICA'),
    ('fatico-juridico', 'fático-jurídico'),
    ('juridicamente', 'juridicamente'),  # no accent needed
    # -ção words
    ('Uniformizacao', 'Uniformização'),
    ('uniformizacao', 'uniformização'),
    ('Interpretacao', 'Interpretação'),
    ('interpretacao', 'interpretação'),
    ('fundamentacao', 'fundamentação'),
    ('demonstracao', 'demonstração'),
    ('flexibilizacao', 'flexibilização'),
    ('judicializacao', 'judicialização'),
    ('reconsideracao', 'reconsideração'),
    ('consideracao', 'consideração'),
    ('desconsideracao', 'desconsideração'),
    ('interposicao', 'interposição'),
    ('contraposicao', 'contraposição'),
    ('distribuicao', 'distribuição'),
    ('modificacao', 'modificação'),
    ('reapreciacao', 'reapreciação'),
    ('apreciacao', 'apreciação'),
    ('verificacao', 'verificação'),
    ('composicao', 'composição'),
    ('Constituicao', 'Constituição'),
    ('constituicao', 'constituição'),
    ('realizacao', 'realização'),
    ('atribuicao', 'atribuição'),
    ('inadmissao', 'inadmissão'),
    ('prestacao', 'prestação'),
    ('Prestacao', 'Prestação'),
    ('protecao', 'proteção'),
    ('concessao', 'concessão'),
    ('correcao', 'correção'),
    ('alteracao', 'alteração'),
    ('exclusao', 'exclusão'),
    ('inclusao', 'inclusão'),
    ('aplicacao', 'aplicação'),
    ('devolucao', 'devolução'),
    ('obrigacao', 'obrigação'),
    ('afericao', 'aferição'),
    ('violacao', 'violação'),
    ('operacao', 'operação'),
    ('situacao', 'situação'),
    ('admissao', 'admissão'),
    ('conclusao', 'conclusão'),
    ('Conclusao', 'Conclusão'),
    ('restricao', 'restrição'),
    ('informacao', 'informação'),
    ('manutencao', 'manutenção'),
    ('posicao', 'posição'),
    ('decisao', 'decisão'),
    ('Decisao', 'Decisão'),
    ('omissao', 'omissão'),
    ('relacao', 'relação'),
    ('Questao', 'Questão'),
    ('questao', 'questão'),
    ('funcao', 'função'),
    ('nocao', 'noção'),
    ('razao', 'razão'),
    # -ência/-ância words
    ('jurisprudencia', 'jurisprudência'),
    ('deficiencia', 'deficiência'),
    ('Deficiencia', 'Deficiência'),
    ('insuficiencia', 'insuficiência'),
    ('competencia', 'competência'),
    ('divergencia', 'divergência'),
    ('subsistencia', 'subsistência'),
    ('consequencia', 'consequência'),
    ('circunstancia', 'circunstância'),
    ('incidencia', 'incidência'),
    ('relevancia', 'relevância'),
    ('providencia', 'providência'),
    ('experiencia', 'experiência'),
    ('existencia', 'existência'),
    ('referencia', 'referência'),
    ('instancia', 'instância'),
    ('regencia', 'regência'),
    ('ausencia', 'ausência'),
    ('Assistencia', 'Assistência'),
    ('assistencia', 'assistência'),
    # -ório/-ória
    ('declaratorios', 'declaratórios'),
    ('declaratorio', 'declaratório'),
    ('embargatorio', 'embargatório'),
    ('subsidiario', 'subsidiário'),
    ('subsidiaria', 'subsidiária'),
    ('necessario', 'necessário'),
    ('necessaria', 'necessária'),
    ('Plenario', 'Plenário'),
    ('contrario', 'contrário'),
    ('contraria', 'contrária'),
    # -ático/-ético/-ídico etc.
    ('juridico', 'jurídico'),
    ('juridica', 'jurídica'),
    ('especificos', 'específicos'),
    ('especifico', 'específico'),
    ('especifica', 'específica'),
    ('economico', 'econômico'),
    ('economica', 'econômica'),
    ('fatico', 'fático'),
    ('fatica', 'fática'),
    ('identica', 'idêntica'),
    ('identico', 'idêntico'),
    ('retorico', 'retórico'),
    ('aritmetica', 'aritmética'),
    ('logica', 'lógica'),
    ('logico', 'lógico'),
    ('medico', 'médico'),
    ('medica', 'médica'),
    ('analogas', 'análogas'),
    # -imo/-ulo/-eo
    ('minimo', 'mínimo'),
    ('minima', 'mínima'),
    ('minimas', 'mínimas'),
    ('quinquidio', 'quinquídio'),
    ('nucleo', 'núcleo'),
    ('calculo', 'cálculo'),
    ('conteudo', 'conteúdo'),
    ('salario', 'salário'),
    ('proprio', 'próprio'),
    ('propria', 'própria'),
    # -nico/-nica
    ('unico', 'único'),
    ('unica', 'única'),
    ('Organica', 'Orgânica'),
    # Verb forms
    ('impoe', 'impõe'),
    ('pressupoe', 'pressupõe'),
    ('dispoe', 'dispõe'),
    # Other common words
    ('Justica', 'Justiça'),
    ('justica', 'justiça'),
    ('Uniao', 'União'),
    ('tambem', 'também'),
    ('porem', 'porém'),
    ('ate ', 'até '),
    ('alem ', 'além '),
    ('venia', 'vênia'),
    ('analise', 'análise'),
    ('ambito', 'âmbito'),
    ('carater', 'caráter'),
    ('farmacos', 'fármacos'),
    ('notoria', 'notória'),
    ('irmaos', 'irmãos'),
    ('razoes', 'razões'),
    ('condicoes', 'condições'),
    ('acoes', 'ações'),
    ('padroes', 'padrões'),
    ('tramite', 'trâmite'),
    ('topico', 'tópico'),
    ('obice', 'óbice'),
    ('orgao', 'órgão'),
    ('Orgao', 'Órgão'),
    ('acordao', 'acórdão'),
    ('Acordao', 'Acórdão'),
    ('materia', 'matéria'),
    ('criterio ', 'critério '),
    ('criterios', 'critérios'),
    ('Nao ', 'Não '),
    ('nao ', 'não '),
    ('nao,', 'não,'),
    ('nao.', 'não.'),
    ('nao;', 'não;'),
]

for old, new in replacements:
    text = text.replace(old, new)

# Fix 'e' -> 'é' only in specific patterns (isolated word meaning "is")
# This is tricky - only replace isolated 'e' meaning "is", not conjunction "e" (and)
# We'll skip this blanket replacement as it's too error-prone

with open('Entrada/2026/Março/embargos_declaracao_5028845-33.2023.4.04.7200.txt', 'w', encoding='utf-8') as f:
    f.write(text)

print('Acentos corrigidos com sucesso')
print(f'Tamanho: {len(text)} caracteres')
